server:
  port: ${CONFIG_SERVER_PORT:8011}

spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${REGISTRY_SERVER_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

security:
  user:
    name: ${CONFIG_SERVICE_USERNAME:root}
    password: ${CONFIG_SERVICE_PASSWORD:password}
