# for security, hidden the header 'x-application-context'
management.server:
  add-application-context-header: false

spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
      - id: feign
        uri: lb://clientfeign
        predicates:
        - Path=/feign/**
        filters:
        - StripPrefix=1
      - id: ribbon
        uri: lb://clientribbon
        predicates:
        - Path=/ribbon/**
        filters:
        - StripPrefix=1
